apiVersion: v1
kind: Secret
metadata:
  name: opsguard-secrets
  namespace: opsguard
type: Opaque
data:
  # Base64 encoded values - CHANGE THESE IN PRODUCTION!
  # To encode: echo -n 'your-value' | base64
  
  # Database credentials
  # Default: opsguard (b3BzZ3VhcmQ=)
  POSTGRES_USER: b3BzZ3VhcmQ=
  
  # Default: opsguard_secure_password_change_me
  POSTGRES_PASSWORD: b3BzZ3VhcmRfc2VjdXJlX3Bhc3N3b3JkX2NoYW5nZV9tZQ==
  
  # NextAuth secret - Default: change_this_to_a_random_secret_in_production
  NEXTAUTH_SECRET: Y2hhbmdlX3RoaXNfdG9fYV9yYW5kb21fc2VjcmV0X2luX3Byb2R1Y3Rpb24=

---
# To create your own secret values, run:
# echo -n 'your-username' | base64
# echo -n 'your-password' | base64
# echo -n 'your-nextauth-secret' | base64
# 
# Or use kubectl:
# kubectl create secret generic opsguard-secrets \
#   --from-literal=POSTGRES_USER=opsguard \
#   --from-literal=POSTGRES_PASSWORD=your-secure-password \
#   --from-literal=NEXTAUTH_SECRET=your-nextauth-secret \
#   -n opsguard
