name: 💡 Feature Request
description: Suggest an idea or enhancement for OpsKnight
title: '[FEAT] '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! We love hearing from the community.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: "I'm always frustrated when I have to manually update the schedule everyday..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: 'I would like a button that auto-syncs the calendar...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.

  - type: dropdown
    id: importance
    attributes:
      label: Importance
      description: How critical is this feature to your workflow?
      options:
        - 'Nice to have'
        - 'Important'
        - 'Critical / Blocker'

  - type: checkboxes
    id: help
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a PR for this feature
